### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by vahid18u** [usablica/persian.js#54]
it returns error : 

persianJs("0")
      .englishNumber()
      .toString();

**Comment by TheYahya** [comment]
Hi @vahid18u,
Thank you for submitting an issue, Could you tell me what's the error that you get? Because it's seem fine to me as you can see below.

<img width="575" alt="Screen Shot 2019-11-28 at 11 14 05 PM" src="https://user-images.githubusercontent.com/15307244/69829405-11d59c80-1235-11ea-947e-8c47e579ca24.png">

**Comment by vahid18u** [comment]
I'm sorry I see your message now. 
I run the code today again and I see no error now. version 0.4.0
Thanks

**Comment by TheYahya** [comment]
Thanks @vahid18u
